;;; island-theme.el --- Material You theme generated by matugen -*- lexical-binding: t; -*-
;;
;; Author: Vladislav <nikko@cachyos-x8664>
;; Homepage: https://github.com/nikko/iris-theme
;; Package-Requires: ((emacs "24.3") (doom-themes "2.2.1"))
;;
;; This file is not part of GNU Emacs.
;;
;;; Commentary:
;;
;;  Generated file — do not edit.  The source template lives in
;;  the shell's Templates/Matugen/emacs.el and is rendered by matugen on every
;;  wallpaper change.  Colors come from the Material You scheme derived from
;;  the current wallpaper: surfaces and accents are the Material roles, while
;;  red/green/yellow/... are the harmonized custom colors declared in
;;  the shell's Templates/matugen-base.toml.
;;
;;; Code:

(require 'doom-themes)

(defgroup island-theme nil
  "Options for the matugen theme."
  :group 'doom-themes)

(def-doom-theme island
  "A Material You theme generated from the current wallpaper by matugen."

  ;;;; Color palette
  ;; name        gui                                                    256 16
  ((bg          '("{{colors.surface.default.hex}}"                       nil nil))
   (bg-alt      '("{{colors.surface_container.default.hex}}"             nil nil))
   (fg          '("{{colors.on_surface.default.hex}}"                    nil nil))
   (fg-alt      '("{{colors.on_surface_variant.default.hex}}"            nil nil))

   ;; base0 is the "darkest" end, base8 the "lightest" (inverted in light
   ;; mode, which doom tolerates).
   (base0       '("{{colors.surface_container_lowest.default.hex}}"      nil nil))
   (base1       '("{{colors.surface_container_low.default.hex}}"         nil nil))
   (base2       '("{{colors.surface_container.default.hex}}"             nil nil))
   (base3       '("{{colors.surface_container_high.default.hex}}"        nil nil))
   (base4       '("{{colors.surface_container_highest.default.hex}}"     nil nil))
   (base5       '("{{colors.outline_variant.default.hex}}"               nil nil))
   (base6       '("{{colors.outline.default.hex}}"                       nil nil))
   (base7       '("{{colors.on_surface_variant.default.hex}}"            nil nil))
   (base8       '("{{colors.on_surface.default.hex}}"                    nil nil))

   (grey        base6)
   (red         '("{{colors.red.default.hex}}"                           nil nil))
   (orange      '("{{colors.orange.default.hex}}"                        nil nil))
   (green       '("{{colors.green.default.hex}}"                         nil nil))
   (teal        '("{{colors.cyan.default.hex}}"                          nil nil))
   (yellow      '("{{colors.yellow.default.hex}}"                        nil nil))
   (blue        '("{{colors.blue.default.hex}}"                          nil nil))
   (dark-blue   '("{{colors.primary_fixed_dim.default.hex}}"             nil nil))
   (magenta     '("{{colors.magenta.default.hex}}"                       nil nil))
   (violet      '("{{colors.tertiary.default.hex}}"                      nil nil))
   (cyan        '("{{colors.cyan.default.hex}}"                          nil nil))
   (dark-cyan   '("{{colors.secondary.default.hex}}"                     nil nil))

   ;;;; Face categories — driven by the Material roles so the syntax colors
   ;;;; stay in the same tonal family as the rest of the desktop.
   (highlight      '("{{colors.primary.default.hex}}"                    nil nil))
   (vertical-bar   base2)
   (selection      base2)
   (builtin        '("{{colors.tertiary.default.hex}}"                   nil nil))
   (comments       '("{{colors.outline.default.hex}}"                    nil nil))
   (doc-comments   '("{{colors.on_surface_variant.default.hex}}"         nil nil))
   (constants      '("{{colors.orange.default.hex}}"                     nil nil))
   (functions      '("{{colors.tertiary.default.hex}}"                   nil nil))
   (keywords       '("{{colors.primary.default.hex}}"                    nil nil))
   (methods        '("{{colors.tertiary.default.hex}}"                   nil nil))
   (operators      '("{{colors.on_surface_variant.default.hex}}"         nil nil))
   (type           '("{{colors.secondary.default.hex}}"                  nil nil))
   (strings        '("{{colors.green.default.hex}}"                      nil nil))
   (variables      '("{{colors.on_surface.default.hex}}"                 nil nil))
   (numbers        '("{{colors.orange.default.hex}}"                     nil nil))
   (region         base2)
   (error          '("{{colors.error.default.hex}}"                      nil nil))
   (warning        yellow)
   (success        green)
   (vc-modified    yellow)
   (vc-added       green)
   (vc-deleted     red)

   ;;;; Custom
   (modeline-bg     bg-alt)
   (modeline-bg-alt bg)
   (modeline-fg     fg)
   (modeline-fg-alt fg-alt))

  ;;;; Face overrides
  (((line-number              &override) :foreground base6)
   ((line-number-current-line &override) :foreground highlight :weight 'bold)
   (cursor  :background highlight)
   (mode-line          :background modeline-bg     :foreground modeline-fg)
   (mode-line-inactive :background modeline-bg-alt :foreground modeline-fg-alt)
   ((font-lock-comment-face &override) :slant 'italic)
   (doom-modeline-bar :background highlight)
   (tooltip :background bg-alt :foreground fg)

   ;;;; Selection — the container tones sit close to bg, so these are
   ;;;; blended off the accent instead.
   (region  :background (doom-blend highlight bg 0.15) :extend t)
   (hl-line :background (doom-blend fg bg 0.07))
   (vertico-current :background (doom-blend highlight bg 0.22)
                    :foreground fg :extend t)
   (vertico-group-title :foreground highlight :weight 'bold)

   ;;;; Match highlighting
   ((completions-common-part &override) :foreground highlight :weight 'bold)
   (orderless-match-face-0 :foreground highlight :weight 'bold)
   (orderless-match-face-1 :foreground magenta   :weight 'bold)
   (orderless-match-face-2 :foreground green     :weight 'bold)
   (orderless-match-face-3 :foreground yellow    :weight 'bold))

  ;;;; Variable overrides
  ())

(provide-theme 'island)
;;; island-theme.el ends here
