[General]
background_color="{{colors.surface.default.hex}}"
surface="{{colors.surface_container.default.hex}}"
foreground="{{colors.on_surface.default.hex}}"
dim="{{colors.surface_variant.default.hex}}"
accent="{{colors.primary.default.hex}}"
accentAlt="{{colors.secondary.default.hex}}"
error="{{colors.error.default.hex}}"
success="{{colors.green.default.hex}}"
warning="{{colors.yellow.default.hex}}"
